modLoader="javafml"
loaderVersion="[47,)"
license="Academic Free License v3.0"

[[mods]]
modId="platformercodegenerator"
version="1.0.0"
displayName="platformerCodegenerator"
displayURL="https://nourl.net"
credits="Made By Tototcs"
authors="Tototcs"

[[dependencies.platformercodegenerator]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




